name: Tests

on: [push, pull_request]
env:
  pyversion: 3.9

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.pyversion }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.pyversion }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest scikit-learn
          pip install pytorch-lightning
          pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest tests
